[33m[nodemon] 2.0.3[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching path(s): *.*[39m
[33m[nodemon] watching extensions: js,mjs,json[39m
[32m[nodemon] starting `node ./bin/www 2`[39m
socket set successfull with reference to 'socketio'
Database Connected
[0mPOST /createRoom [32m200 [0m11215.838 ms - 153[0m
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rq_5b' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rq_-2' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr0Gy' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr0Zk' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr0sq' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr13V' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr1I0' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr1fv' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr1tm' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr2Ex' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr2Q7' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr2l2' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr2xr' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr3FN' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr3P9' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr3jd' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr40Y' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr4Aq' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr4Vr' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
user object { roomId: 'debanjanb4ck9gus80n',
  user: '[object Object]',
  EIO: '3',
  transport: 'polling',
  t: 'N6rr4sP' }
USER >>> [object Object]
Missing error handler on `socket`.
TypeError: Cannot read property 'then' of undefined
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:34)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
    at XHR.Transport.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transport.js:105:8)
    at callback (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\transports\polling.js:208:10)
    at Object.exports.decodePayload (D:\Innovation Challenge\vid.co\node_modules\engine.io-parser\lib\index.js:311:18)
(node:14412) UnhandledPromiseRejectionWarning: ReferenceError: promise is not defined
    at Promise (D:\Innovation Challenge\vid.co\routes\index.js:204:5)
    at new Promise (<anonymous>)
    at authUser (D:\Innovation Challenge\vid.co\routes\index.js:187:17)
    at Array.io.of.use (D:\Innovation Challenge\vid.co\routes\index.js:31:9)
    at run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:124:11)
    at Namespace.run (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:136:3)
    at Namespace.add (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\namespace.js:164:8)
    at Client.doConnect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:97:20)
    at Client.connect (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:66:17)
    at Client.ondecoded (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:209:10)
    at Decoder.Emitter.emit (D:\Innovation Challenge\vid.co\node_modules\component-emitter\index.js:133:20)
    at Decoder.add (D:\Innovation Challenge\vid.co\node_modules\socket.io-parser\index.js:251:12)
    at Client.ondata (D:\Innovation Challenge\vid.co\node_modules\socket.io\lib\client.js:195:18)
    at Socket.emit (events.js:189:13)
    at Socket.onPacket (D:\Innovation Challenge\vid.co\node_modules\engine.io\lib\socket.js:109:14)
    at XHR.emit (events.js:189:13)
(node:14412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
ROOM >>> { host: { hostName: 'debanjan', hostId: 'b4ck9gus80o' },
  createdAt: 2020-04-26T09:31:03.409Z,
  _id: 5ea554ef6c8c02384cd0e455,
  meetingId: 'b4ck9gus80p',
  roomId: 'debanjanb4ck9gus80n',
  guests:
   [ { status: true,
       joinedAt: 2020-04-26T09:31:03.409Z,
       leftAt: null,
       isHost: true,
       _id: 5ea554ef6c8c02384cd0e456,
       guestId: 'b4ck9gus80o',
       guestName: 'debanjan' } ],
  roomKey: 'k9gus80q',
  __v: 0 }
^C